language: android

env:
  global:
    - GRADLE_OPTS=-Xmx512m

android:
  components:
    - tools
    - build-tools-27.0.3 # TODO: build gradle without build-tools
    - android-27
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew assemble test --stacktrace
